name: verify
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: .github/actions/setup
      - name: Run Tests
        run: poetry run task test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: .github/actions/setup
      - name: Build project
        run: poetry build
